spring:
  application:
    name: payment
  datasource:
    url: jdbc:postgresql://localhost:5431/paymentdb
    password: postgres
    username: postgres
  cloud:
    function:
      definition: payment;claim;order;
    config:
      enable: true
    stream:
      kafka:
        default:
          producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer:
            enableDlq: false
            autoCommitOnError: true
            autoCommitOffset: true
        binder:
          brokers: localhost:9092
          minPartitionCount: 4
          autoAddPartitions: true
          consumerProperties:
            enable.auto.commit: true
            fetch.max.bytes: 62194560
            session.timeout.ms: 15000
          producerProperties:
            retries: 3
            batch.size: 16384
            buffer.memory: 33554432
            linger.ms: 1
      bindings:
        payment-out-0:
          destination: payment
          content-type: application/json
        claim-in-0:
          destination: claim
          content-type: application/json
          group: payment-group
        order-in-0:
          destination: order
          content-type: application/json
          group: payment-group
cron:
  bank-api:
    expression: "0 0/5 * * * *"